# 2-Check Consensus Timeout Rules Configuration
# Defines timeout periods and escalation rules for different transaction types

# Default timeout values (in seconds)
defaults:
  base_timeout: 300  # 5 minutes default
  max_timeout: 86400  # 24 hours maximum
  warning_threshold: 0.8  # Warn at 80% of timeout

# Transaction type specific rules
transaction_types:
  # Supplier to Manufacturer transfers
  supplier_to_manufacturer:
    timeout: 3600  # 1 hour
    escalation_levels:
      - level: 1
        at_percent: 50
        action: send_reminder
        notify: [sender, receiver]
      - level: 2
        at_percent: 80
        action: urgent_notification
        notify: [sender, receiver, brand_admin]
      - level: 3
        at_percent: 100
        action: auto_escalate
        notify: [all_stakeholders]
    business_hours_only: true
    timezone: UTC

  # Manufacturer to Retailer transfers
  manufacturer_to_retailer:
    timeout: 7200  # 2 hours
    escalation_levels:
      - level: 1
        at_percent: 50
        action: send_reminder
        notify: [receiver]
      - level: 2
        at_percent: 75
        action: urgent_notification
        notify: [sender, receiver]
      - level: 3
        at_percent: 100
        action: auto_escalate
        notify: [brand_admin, supply_chain_manager]
    business_hours_only: true
    timezone: UTC

  # Retailer to Customer sales
  retailer_to_customer:
    timeout: 172800  # 48 hours
    escalation_levels:
      - level: 1
        at_percent: 25
        action: send_reminder
        notify: [customer]
        channel: email
      - level: 2
        at_percent: 50
        action: send_reminder
        notify: [customer]
        channel: sms
      - level: 3
        at_percent: 90
        action: support_ticket
        notify: [customer_service]
    business_hours_only: false
    timezone: local

  # Quality checks and inspections
  quality_inspection:
    timeout: 1800  # 30 minutes
    escalation_levels:
      - level: 1
        at_percent: 70
        action: urgent_notification
        notify: [quality_manager]
      - level: 2
        at_percent: 100
        action: halt_production
        notify: [production_manager, brand_admin]
    business_hours_only: true
    timezone: UTC

# Trust-based timeout adjustments
trust_adjustments:
  high_trust:
    score_threshold: 0.9
    timeout_multiplier: 1.5  # 50% more time for trusted partners
    auto_confirm_threshold: 0.95  # Auto-confirm if trust > 95%
  
  medium_trust:
    score_threshold: 0.7
    timeout_multiplier: 1.0  # Standard timeout
  
  low_trust:
    score_threshold: 0.5
    timeout_multiplier: 0.8  # 20% less time for low trust
    require_evidence: true
  
  new_relationship:
    score_threshold: 0.0
    timeout_multiplier: 0.7  # 30% less time for new relationships
    require_evidence: true
    additional_checks: true

# Business hours configuration
business_hours:
  monday:
    start: "09:00"
    end: "18:00"
  tuesday:
    start: "09:00"
    end: "18:00"
  wednesday:
    start: "09:00"
    end: "18:00"
  thursday:
    start: "09:00"
    end: "18:00"
  friday:
    start: "09:00"
    end: "18:00"
  saturday:
    start: "10:00"
    end: "14:00"
  sunday:
    closed: true

# Holiday handling
holidays:
  mode: extend  # Options: extend, pause, ignore
  extension_hours: 24  # Add 24 hours for each holiday

# Notification templates
notification_templates:
  reminder:
    subject: "Action Required: Confirm Receipt of {item_type}"
    priority: normal
  
  urgent:
    subject: "URGENT: Pending Confirmation for {item_type}"
    priority: high
  
  escalation:
    subject: "ESCALATED: Unconfirmed Transfer of {item_type}"
    priority: critical

# Auto-escalation rules
auto_escalation:
  enabled: true
  conditions:
    - type: timeout_exceeded
      action: create_dispute
      severity: medium
    
    - type: multiple_timeouts
      count: 3
      window: 604800  # 7 days
      action: flag_relationship
      severity: high
    
    - type: pattern_detected
      pattern: suspicious_routing
      action: security_alert
      severity: critical

# Evidence requirements
evidence_requirements:
  low_trust:
    - shipping_document
    - photo_proof
    - timestamp_verification
  
  dispute:
    - shipping_document
    - photo_proof
    - gps_location
    - witness_confirmation
  
  high_value:
    threshold: 10000  # USD
    required:
      - video_proof
      - multi_signature
      - insurance_confirmation