# consensus/2check/config/trust-scoring.yaml
# Trust scoring system configuration

trust_scoring:
  enabled: true
  initial_score: 50
  max_score: 200
  min_score: 0
  
  # Score modifications
  score_changes:
    # Positive actions
    positive:
      successful_transaction:
        base_points: 1
        description: "Transaction completed successfully"
        
      on_time_confirmation:
        base_points: 0.5
        description: "Confirmed within expected timeframe"
        multiplier:
          - condition: "confirmation_time < timeout * 0.25"
            value: 2.0  # Very fast confirmation
          - condition: "confirmation_time < timeout * 0.5"
            value: 1.5  # Fast confirmation
            
      dispute_resolved_favorably:
        base_points: 2
        description: "Dispute resolved in participant's favor"
        
      accurate_reporting:
        base_points: 1
        description: "Accurate issue reporting leading to resolution"
        
      batch_success:
        base_points: 0.1
        description: "Per item in successful batch operation"
        max_per_batch: 5
        
    # Negative actions
    negative:
      late_confirmation:
        base_points: -0.5
        description: "Confirmed after reminder"
        multiplier:
          - condition: "confirmation_after_reminders >= 2"
            value: 2.0  # Very late
            
      caused_timeout:
        base_points: -2
        description: "Failed to confirm, causing timeout"
        
      disputed_transaction:
        base_points: -5
        description: "Transaction was disputed"
        multiplier:
          - condition: "dispute.resolution == 'at_fault'"
            value: 2.0  # Found at fault
            
      false_claim:
        base_points: -10
        description: "Made false or fraudulent claim"
        
      emergency_stop_unjustified:
        base_points: -8
        description: "Used emergency stop without valid reason"
        
  # Value-based multipliers
  transaction_value_multipliers:
    - min_value: 0
      max_value: 1000
      multiplier: 1.0
      
    - min_value: 1000
      max_value: 10000
      multiplier: 1.2
      
    - min_value: 10000
      max_value: 50000
      multiplier: 1.5
      
    - min_value: 50000
      max_value: null
      multiplier: 2.0
      
  # Trust levels and benefits
  trust_levels:
    - name: "new"
      min_score: 0
      max_score: 50
      color: "gray"
      benefits:
        - "manual_verification_required"
        - "no_batch_operations"
        - "standard_timeouts"
        - "prepayment_may_be_required"
        
    - name: "basic"
      min_score: 50
      max_score: 100
      color: "bronze"
      benefits:
        - "small_transactions_auto_approved"  # < $1000
        - "standard_timeouts"
        - "basic_support"
        
    - name: "trusted"
      min_score: 100
      max_score: 150
      color: "silver"
      benefits:
        - "most_transactions_auto_approved"  # < $10000
        - "extended_timeouts"  # +50%
        - "batch_operations_allowed"
        - "priority_support"
        - "self_dispute_resolution"  # For minor issues
        
    - name: "premium"
      min_score: 150
      max_score: 200
      color: "gold"
      benefits:
        - "all_transactions_auto_approved"
        - "maximum_timeouts"  # +100%
        - "unlimited_batch_operations"
        - "dedicated_support"
        - "api_access_granted"
        - "preferential_rates"
        
  # Automation rules based on trust
  automation_rules:
    - name: "auto_approve_small"
      condition:
        trust_score: 50
        transaction_value: 1000
        operator: "less_than"
      action: "auto_approve_after_24h"
      
    - name: "auto_approve_medium"
      condition:
        trust_score: 100
        transaction_value: 10000
        operator: "less_than"
      action: "auto_approve_after_48h"
      
    - name: "auto_approve_trusted"
      condition:
        trust_score: 150
        transaction_value: 50000
        operator: "less_than"
      action: "auto_approve_after_72h"
      
    - name: "instant_approve_premium"
      condition:
        trust_score: 180
        repeat_transaction: true
      action: "auto_approve_immediate"
      
  # Trust score decay (to prevent inactive accounts maintaining high trust)
  decay:
    enabled: true
    check_interval: 30  # days
    inactivity_threshold: 90  # days
    decay_rate: 0.95  # Multiply score by this each interval
    min_score_after_decay: 50  # Don't go below this
    
  # Recovery mechanisms
  recovery:
    dispute_recovery:
      enabled: true
      clean_record_period: 180  # days
      bonus_points: 5
      
    volume_recovery:
      enabled: true
      threshold: 20  # successful transactions
      bonus_points: 10