# Brand Configuration Template
# This file defines all configurable parameters for a luxury brand's blockchain network

brand:
  id: "example-luxury-brand"
  name: "Example Luxury Brand"
  description: "High-end luxury goods manufacturer"
  
network:
  # Network topology configuration
  organizations:
    - id: "brand"
      name: "${BRAND_NAME}"
      type: "brand_owner"
      mspId: "${BRAND_NAME}MSP"
      peers:
        - name: "peer0"
          port: 7051
          chaincodePort: 7052
          operationsPort: 9443
        - name: "peer1"
          port: 8051
          chaincodePort: 8052
          operationsPort: 9444
    
    - id: "supplier1"
      name: "Premium Materials Supplier"
      type: "supplier"
      mspId: "Supplier1MSP"
      peers:
        - name: "peer0"
          port: 9051
          chaincodePort: 9052
          operationsPort: 9445
    
    - id: "manufacturer1"
      name: "Certified Manufacturer"
      type: "manufacturer"
      mspId: "Manufacturer1MSP"
      peers:
        - name: "peer0"
          port: 10051
          chaincodePort: 10052
          operationsPort: 9446
    
    - id: "retailer1"
      name: "Authorized Retailer"
      type: "retailer"
      mspId: "Retailer1MSP"
      peers:
        - name: "peer0"
          port: 11051
          chaincodePort: 11052
          operationsPort: 9447
  
  # Orderer configuration
  orderers:
    - name: "orderer1"
      port: 7050
      operationsPort: 8443
      organization: "orderer"
    - name: "orderer2"
      port: 8050
      operationsPort: 8444
      organization: "orderer"
    - name: "orderer3"
      port: 9050
      operationsPort: 8445
      organization: "orderer"
  
  # Channel configuration
  channels:
    - name: "luxury-supply-chain"
      consortium: "LuxuryConsortium"
      application:
        organizations:
          - "brand"
          - "supplier1"
          - "manufacturer1"
          - "retailer1"
        capabilities:
          - "V2_5"
        policies:
          readers: "ANY"
          writers: "ALL"
          admins: "MAJORITY"
          endorsement: "MAJORITY"

# Consensus Configuration
consensus:
  type: "proof-of-luxury-authority"
  parameters:
    # Stakeholder weights for consensus
    weights:
      brand_owner: 40
      supplier: 20
      manufacturer: 20
      retailer: 15
      ai_advisory: 5
    
    # Minimum participation threshold
    minParticipation: 70
    
    # Reputation scoring
    reputation:
      enabled: true
      initialScore: 100
      maxScore: 150
      minScore: 0
      factors:
        - type: "transaction_accuracy"
          weight: 0.3
        - type: "verification_speed"
          weight: 0.2
        - type: "dispute_resolution"
          weight: 0.3
        - type: "compliance"
          weight: 0.2
    
    # AI advisory configuration
    aiAdvisory:
      enabled: true
      confidenceThreshold: 0.85
      vetoThreshold: 0.95
      models:
        - "authenticity_verification"
        - "anomaly_detection"
        - "pattern_recognition"

# Product Configuration
products:
  categories:
    - id: "handbags"
      name: "Luxury Handbags"
      attributes:
        - "serial_number"
        - "model"
        - "materials"
        - "craftsman_id"
        - "production_date"
        - "authenticity_certificate"
      verificationRequirements:
        - "visual_inspection"
        - "material_analysis"
        - "craftsmanship_verification"
        - "serial_validation"
    
    - id: "watches"
      name: "Luxury Timepieces"
      attributes:
        - "serial_number"
        - "model"
        - "movement_type"
        - "materials"
        - "complications"
        - "production_date"
      verificationRequirements:
        - "movement_verification"
        - "serial_validation"
        - "component_analysis"
        - "timing_accuracy"

# Integration Configuration
integrations:
  erp:
    enabled: true
    type: "simulated"  # Options: simulated, sap, oracle, custom
    endpoints:
      inventory: "/api/v1/inventory"
      orders: "/api/v1/orders"
      products: "/api/v1/products"
  
  ai:
    enabled: true
    service: "internal"
    endpoints:
      analyze: "/api/v1/analyze"
      train: "/api/v1/train"
      verify: "/api/v1/verify"

# Security Configuration
security:
  tls:
    enabled: true
    clientAuthRequired: true
  
  identity:
    provider: "fabric-ca"
    adminIdentity: "${BRAND_NAME}Admin"
    userEnrollment:
      maxEnrollments: -1
      affiliation: "${BRAND_NAME}.department1"