# config/brands/example-brand/network-config.yaml
# Updated with 2-Check consensus configuration

brand:
  id: "luxe-bags"
  name: "luxebags"
  description: "Premium luxury handbag manufacturer"
  
network:
  organizations:
    - id: "luxebags"
      name: "LuxeBags"
      type: "brand_owner"
      mspId: "LuxeBagsMSP"
      peers:
        - name: "peer0"
          port: 7051
          chaincodePort: 7052
          operationsPort: 9443
        - name: "peer1"
          port: 8051
          chaincodePort: 8052
          operationsPort: 9444
    
    - id: "italianleather"
      name: "Italian Leather Co"
      type: "supplier"
      mspId: "ItalianLeatherMSP"
      peers:
        - name: "peer0"
          port: 9051
          chaincodePort: 9052
          operationsPort: 9445
    
    - id: "craftworkshop"
      name: "Master Craft Workshop"
      type: "manufacturer"
      mspId: "CraftWorkshopMSP"
      peers:
        - name: "peer0"
          port: 10051
          chaincodePort: 10052
          operationsPort: 9446
    
    - id: "luxuryretail"
      name: "Luxury Retail Boutique"
      type: "retailer"
      mspId: "LuxuryRetailMSP"
      peers:
        - name: "peer0"
          port: 11051
          chaincodePort: 11052
          operationsPort: 9447
  
  orderers:
    - name: "orderer1"
      port: 7050
      operationsPort: 8443
      organization: "orderer"
    - name: "orderer2"
      port: 8050
      operationsPort: 8444
      organization: "orderer"
    - name: "orderer3"
      port: 9050
      operationsPort: 8445
      organization: "orderer"
  
  channels:
    - name: "luxury-supply-chain"
      consortium: "LuxuryConsortium"
      application:
        organizations:
          - "luxebags"
          - "italianleather"
          - "craftworkshop"
          - "luxuryretail"

# NEW: 2-Check Consensus Configuration
consensus:
  type: "2-check"
  
  # Basic parameters
  parameters:
    require_dual_confirmation: true
    auto_validate: true
    enable_disputes: true
    enable_emergency_stop: true
    
  # Timeout rules (hours)
  timeouts:
    default: 72
    high_value: 24      # For items > $10,000
    trusted_partner: 168 # 1 week for trust score > 100
    
  # Trust scoring
  trust:
    enabled: true
    initial_score: 50
    score_factors:
      successful_transaction: +1
      on_time_confirmation: +0.5
      dispute_resolved: +2
      timeout_caused: -2
      false_claim: -10
      
  # Automation based on trust
  automation:
    - trust_level: 50
      benefits: ["small_tx_auto_approve"]
      threshold: 1000
    - trust_level: 100
      benefits: ["batch_operations", "extended_timeouts"]
      threshold: 10000
    - trust_level: 150
      benefits: ["instant_approval", "api_access"]
      threshold: 50000
      
  # Notification settings
  notifications:
    channels: ["email", "in_app"]
    reminder_schedule: [24, 12, 1] # hours before timeout

products:
  categories:
    - id: "handbags"
      name: "Luxury Handbags"
      attributes:
        - "serial_number"
        - "model"
        - "leather_type"
        - "hardware_material"
        - "craftsman_id"
        - "production_date"
        - "authenticity_certificate"
        - "dimensions"
        - "weight"
      verificationRequirements:
        - "leather_verification"
        - "hardware_inspection"
        - "stitching_pattern_analysis"
        - "serial_validation"
        - "craftsman_signature_verification"
      ai_models:
        - "leather_authenticity_model"
        - "stitching_pattern_recognition"
        - "hardware_quality_assessment"
        - "logo_verification"

integrations:
  erp:
    enabled: false
    type: "simulated"
    endpoints:
      inventory: "/api/v1/inventory"
      orders: "/api/v1/orders"
      products: "/api/v1/products"
  ai:
    enabled: false
    service: "internal"
    endpoints:
      analyze: "/api/v1/analyze"
      train: "/api/v1/train"
      verify: "/api/v1/verify"

security:
  tls:
    enabled: true
    clientAuthRequired: true
  identity:
    provider: "fabric-ca"
    adminIdentity: "LuxeBagsAdmin"