# Channel configuration for Luxe Bags luxury supply chain
# Using V2_0 capabilities for compatibility
# No system channel - using channel participation API

Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../network/organizations/ordererOrganizations/orderer.${BRAND_DOMAIN}/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"

  - &LuxeBags
    Name: LuxeBagsMSP
    ID: LuxeBagsMSP
    MSPDir: ../network/organizations/peerOrganizations/luxebags.${BRAND_DOMAIN}/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('LuxeBagsMSP.admin', 'LuxeBagsMSP.peer', 'LuxeBagsMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('LuxeBagsMSP.admin', 'LuxeBagsMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('LuxeBagsMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('LuxeBagsMSP.peer')"

  - &ItalianLeather
    Name: ItalianLeatherMSP
    ID: ItalianLeatherMSP
    MSPDir: ../network/organizations/peerOrganizations/italianleather.${BRAND_DOMAIN}/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('ItalianLeatherMSP.admin', 'ItalianLeatherMSP.peer', 'ItalianLeatherMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('ItalianLeatherMSP.admin', 'ItalianLeatherMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('ItalianLeatherMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('ItalianLeatherMSP.peer')"

  - &CraftWorkshop
    Name: CraftWorkshopMSP
    ID: CraftWorkshopMSP
    MSPDir: ../network/organizations/peerOrganizations/craftworkshop.${BRAND_DOMAIN}/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('CraftWorkshopMSP.admin', 'CraftWorkshopMSP.peer', 'CraftWorkshopMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('CraftWorkshopMSP.admin', 'CraftWorkshopMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('CraftWorkshopMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('CraftWorkshopMSP.peer')"

  - &LuxuryRetail
    Name: LuxuryRetailMSP
    ID: LuxuryRetailMSP
    MSPDir: ../network/organizations/peerOrganizations/luxuryretail.${BRAND_DOMAIN}/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('LuxuryRetailMSP.admin', 'LuxuryRetailMSP.peer', 'LuxuryRetailMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('LuxuryRetailMSP.admin', 'LuxuryRetailMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('LuxuryRetailMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('LuxuryRetailMSP.peer')"

# Capabilities - Using V2_0 for compatibility
Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true

  Orderer: &OrdererCapabilities
    V2_0: true

  Application: &ApplicationCapabilities
    V2_0: true

# Application defaults
Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

# Orderer defaults
Orderer: &OrdererDefaults
  OrdererType: etcdraft
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

# Channel defaults
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

# Profiles
Profiles:
  # Channel genesis for application channel
  LuxurySupplyChain:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      OrdererType: etcdraft
      EtcdRaft:
        Consenters:
          - Host: orderer1.orderer.${BRAND_DOMAIN}
            Port: 7050
            ClientTLSCert: ../network/organizations/ordererOrganizations/orderer.${BRAND_DOMAIN}/orderers/orderer1.orderer.${BRAND_DOMAIN}/tls/server.crt
            ServerTLSCert: ../network/organizations/ordererOrganizations/orderer.${BRAND_DOMAIN}/orderers/orderer1.orderer.${BRAND_DOMAIN}/tls/server.crt
          - Host: orderer2.orderer.${BRAND_DOMAIN}
            Port: 8050
            ClientTLSCert: ../network/organizations/ordererOrganizations/orderer.${BRAND_DOMAIN}/orderers/orderer2.orderer.${BRAND_DOMAIN}/tls/server.crt
            ServerTLSCert: ../network/organizations/ordererOrganizations/orderer.${BRAND_DOMAIN}/orderers/orderer2.orderer.${BRAND_DOMAIN}/tls/server.crt
          - Host: orderer3.orderer.${BRAND_DOMAIN}
            Port: 9050
            ClientTLSCert: ../network/organizations/ordererOrganizations/orderer.${BRAND_DOMAIN}/orderers/orderer3.orderer.${BRAND_DOMAIN}/tls/server.crt
            ServerTLSCert: ../network/organizations/ordererOrganizations/orderer.${BRAND_DOMAIN}/orderers/orderer3.orderer.${BRAND_DOMAIN}/tls/server.crt
      Addresses:
        - orderer1.orderer.${BRAND_DOMAIN}:7050
        - orderer2.orderer.${BRAND_DOMAIN}:8050
        - orderer3.orderer.${BRAND_DOMAIN}:9050
      Organizations:
        - *OrdererOrg
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *LuxeBags
        - *ItalianLeather
        - *CraftWorkshop
        - *LuxuryRetail